# Generated by Django 3.0.8 on 2020-07-10 20:56

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.TextField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('code', models.IntegerField()),
                ('sensitive_data', django_cryptography.fields.encrypt(models.CharField(max_length=50))),
            ],
        ),
        migrations.CreateModel(
            name='SessionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=50)),
                ('channel', models.TextField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('score', models.CharField(blank=True, max_length=5, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('estimate_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.EstimateSession')),
            ],
        ),
    ]
