# Generated by Django 3.0.7 on 2020-06-24 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimatesession',
            name='created_by',
        ),
    ]
