# Generated by Django 3.0.8 on 2020-07-11 09:11

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_init'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimatesession',
            name='sensitive_data',
        ),
        migrations.AddField(
            model_name='estimatesession',
            name='session_password',
            field=django_cryptography.fields.encrypt(models.CharField(default='', max_length=128)),
            preserve_default=False,
        ),
    ]
