# Generated by Django 3.0.7 on 2020-06-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_estimatesession_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatesession',
            name='code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
