# Generated by Django 3.0.7 on 2020-06-26 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_estimatesession_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('score', models.CharField(blank=True, max_length=5, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('estimate_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.EstimateSession')),
            ],
        ),
    ]
