# Generated by Django 3.0.7 on 2020-06-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sessionentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionentry',
            name='channel',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
